# -*- coding: utf-8 -*-
"""Overlay_Analysis(sample_Code)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrSiP2zYJ2ANzOJKvppjHedVSlosJJvR
"""

from google.colab import drive
drive.mount('/content/drive/')

!pip install rasterio rioxarray xarray matplotlib

import os
import numpy as np
import rasterio
import matplotlib.pyplot as plt

base_path = '/content/drive/MyDrive/Sample_Code/Raster_Layer'
raster_files = [
    os.path.join(base_path, 'amenity_index.tif'),
    os.path.join(base_path, 'convenience_index.tif'),
    os.path.join(base_path, 'health_index.tif'),
    os.path.join(base_path, 'safety_index.tif'),
]

stack = []
nodata_values = []
for p in raster_files:
    with rasterio.open(p) as src:
        arr = src.read(1).astype('float64')
        nodata = src.nodatavals[0]
        if nodata is not None:
            arr[arr == nodata] = np.nan
        stack.append(arr)
        nodata_values.append(nodata)

stack = np.stack(stack, axis=0)
print('Stack shape:', stack.shape)

weights = np.array([0.25, 0.25, 0.25, 0.25]) #i used equal weights here for simpler calculations
def minmax_normalize(arr):
    amin = np.nanmin(arr)
    amax = np.nanmax(arr)
    if np.isclose(amax, amin):
        return np.full_like(arr, np.nan)
    return (arr - amin) / (amax - amin)

norm_stack = np.array([minmax_normalize(stack[i]) for i in range(stack.shape[0])])
weighted = np.nansum(norm_stack * weights[:, None, None], axis=0)
all_nan_mask = np.all(np.isnan(stack), axis=0)
weighted[all_nan_mask] = np.nan

plt.figure(figsize=(8,6))
plt.title('Weighted index (0-1)')
plt.imshow(weighted, cmap='viridis')
plt.colorbar(label='index')
plt.axis('off')
plt.savefig('/content/drive/MyDrive/Sample_Code/weighted_overlay_map.png', dpi=300, bbox_inches='tight')
plt.show()

out_tif = '/content/drive/MyDrive/Sample_Code/weighted_overlay_result.tif'
with rasterio.open(raster_files[0]) as src:
    meta = src.meta.copy()
meta.update({
    'dtype': 'float32',
    'count': 1,
    'nodata': np.nan
})
with rasterio.open(out_tif, 'w', **meta) as dst:
    dst.write(weighted.astype('float32'), 1)

print("GeoTIFF saved to:", out_tif)